# NumPy : Introduction

**NumPy allows you to manipulate data in the form of an array.**

**Complete the missions below using NumPy.**

In [ ]:
import numpy as np # Here we rename numpy as np, it's shorter, and everybody does that
# Mission 1 : Display the version of NumPy you are running (as each library, you can use np.__version__)
np.__version__

'1.26.4'

In [ ]:
# Mission 2 : Create a NumPy array with a length of 3, that contains this 3 floats: 0.8, 0.6, 0.4
# Expected result: array([0.8, 0.6, 0.4])
data_np = np.array([0.8, 0.6, 0.4])
data_np

array([0.8, 0.6, 0.4])

In [5]:
# Mission 3 : Create a function that uses the np.random.random() function to return an array with 10 random elements,
# all of which must be greater than 0.25 and less than 1.0

def random_array():
    return np.random.random(10) * 0.75 + 0.25
print(random_array())



[0.47842078 0.72122301 0.71076995 0.66514603 0.7873649  0.85165664
 0.47011937 0.42708286 0.43801989 0.89273313]


In [ ]:
# Mission 4 : What does the np.empty() method do? Don't just copy the documentation, explain in your own words here

np.empty() crée un nouveau tableau NumPy avec une taille spécifiée

In [13]:
# Mission 5 : Create an array filled with only zeros. You can choose the length of this array.
arr = np.empty([2,3])
arr.fill(0)
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [25]:
# Mission 6 : Create an array filled with 10 random integers.
arr =  np.random.randint(100, size = (5, 2))
print(arr)

[[55 68]
 [82  0]
 [17 16]
 [ 0  9]
 [87 10]]


In [29]:
# Mission 7 : Create an array that contains 50 values randomly selected only from these numbers: 0, 1, 2, 3, 4, 5, 6, 7.
arr= np.random.randint(8, size= (10,5))
print(arr)

[[5 6 7 5 0]
 [4 2 6 5 6]
 [0 2 0 7 5]
 [6 6 6 1 0]
 [4 3 3 6 1]
 [2 7 1 3 4]
 [2 7 4 3 0]
 [5 5 6 3 1]
 [1 4 6 5 0]
 [5 5 0 4 6]]
